# Theme settings
doks:
    baseurl: /mistica-site
    color_theme: mistica # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text:
            image: true
        nav:
            - item_name: Design
              item_url: '#'
            - item_name: Develop
              item_url: '#'
    footer:
        content:
            logo:
                text: Mística DS
                image:
            copyright: Copyright &copy; 2020. - Mística Design System <br>All rights reserved.
        social_list:
            - network_name: facebook
              profile_url: '#'
            - network_name: twitter
              profile_url: '#'
            - network_name: instagram
              profile_url: '#'
            - network_name: youtube
              profile_url: '#'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
