name: SketchTool Export Assets

on:
  push:
    branches:
    - master
    paths:
    - 'mistica-site/docs/documentation-images.sketch'
    
jobs:
  assets:
    runs-on: [self-hosted, macOS]
    steps:
    - uses: actions/checkout@v2

    # Cuando tengamos todas las imagenes pasadas a sketch, podriamos activar este paso
    # - name: Removed assets
    #   run: git rm -r icons/*

    - name: Download & Install Sketch
      run: |
        curl -OL https://sketch.com/download/sketch.zip
        unzip sketch.zip

    - name: Run SketchTool
      run: Sketch.app/Contents/Resources/sketchtool/bin/sketchtool export layers --output=icons mistica-site/docs/documentation-images.sketch

    - name: Add assets
      run: git add -A mistica-site/docs/img/*

    - name: Commit & Push
      run: |    
        git config --global user.name "Yayo"
        git config --global user.email "yceballost@gmail.com"  
        git commit -am "Update sketch imgs"
        git push origin master